### PR TITLE
add etherscan config

### PR DESCRIPTION
**Pull request by millicare**

### CODE REVIEW

**Review by 0xean — CHANGES_REQUESTED** [review]
thanks for the PR @millicare ! 

Can you please update the README.md with the needed steps to verify the contracts since i assume there is a different call to verify the contracts.  

Is this a one-liner for all contracts deployed or do we need to manually pass each address and constructor args into the call in order to verify?

I will give it a try once we have more info.

**Comment by 0xean** [comment]
ref #79

**Comment by millicare** [comment]
You are welcome!
no, there is no need to duplicate for each contracts, so I'd say to make script to detect all contracts and verify them in there at a once programmatically.

**Comment by millicare** [comment]
https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html
image
you can refer this one to make script.

**Comment by millicare** [comment]
once the script works fine, then there would be need to update README file to write command to run script for contract verify.
instead of hardhat command line.

**Comment by 0xean** [comment]
pulling down your changes now to validate. Please remove the [package-lock.json](https://github.com/ElasticSwap/elasticswap/pull/81/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) and re-install using yarn so we can update the yarn.lock appropiately

**Comment by 0xean** [comment]
Sweet - was able to validate that this does indeed work!

Please get the needed changes made and I can merge this and we can get the bountied paid out.  If you are willing to take it to the next step and implement the full script or add it to the deploy scrips when deploying to a non HH environment we could create a seperate bounty for that as well

**Comment by millicare** [comment]
Updated yarn lock file and removed package-lock.json. now you could be able to get this merge.
and I agree to make another bounty for the script, and I will take it tomorrow as it is a bit late here.

**Review by 0xean — APPROVED** [review]
thanks for the contribution!

**Pull request merged**
